
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALPHANUMERIC COMMA HEADING1 NEWLINE SPACE\n    document : sentence\n    \n        word : ALPHANUMERIC\n            | ALPHANUMERIC word\n    \n    sentence : word NEWLINE\n    | word SPACE sentence\n\n\n    \n    heading : HEADING1 sentence\n    '
    
_lr_action_items = {'ALPHANUMERIC':([0,4,6,],[4,4,4,]),'$end':([1,2,5,8,],[0,-1,-4,-5,]),'NEWLINE':([3,4,7,],[5,-2,-3,]),'SPACE':([3,4,7,],[6,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),'sentence':([0,6,],[2,8,]),'word':([0,4,6,],[3,7,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> sentence','document',1,'p_document','prototype.py',27),
  ('word -> ALPHANUMERIC','word',1,'p_word','prototype.py',34),
  ('word -> ALPHANUMERIC word','word',2,'p_word','prototype.py',35),
  ('sentence -> word NEWLINE','sentence',2,'p_sentence','prototype.py',47),
  ('sentence -> word SPACE sentence','sentence',3,'p_sentence','prototype.py',48),
  ('heading -> HEADING1 sentence','heading',2,'p_heading','prototype.py',61),
]
